[package]
name = "hremote-client"
version = "1.0.0"
description = "HRemote — Client de prise en main à distance Hsasoft"
authors = ["Hsasoft"]
license = "MIT"
repository = ""
edition = "2021"

[lib]
name = "hremote_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "hremote-client"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[package.metadata.bundle]
identifier = "io.hsasoft.hremote"
icon = ["icons/icon.ico", "icons/32x32.png", "icons/128x128.png"]

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
